name: Test

on:
  push:
    branches:
      - "*"

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: playground_test
        options: >-
          --health-cmd pg_isready
          --health-interval 2s
          --health-timeout 2s
          --health-retries 20

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost/playground_test

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - name: Cache ruby gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}

      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: Cache npm dependencies
        id: cache-npm-dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/yarn.lock') }}

      - name: Install npm packages
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: ./bin/rails test

      - name: Run system tests
        run: ./bin/rails test:system
